### PR TITLE
Fix off-by-one in string parsing

### LINKED ISSUE #36: String parser accepts some corrupt data.
I need fractions for an app so I checked if I could use this lib.
```
> jsbi.BigInt(" 123234 ")
JSBI [ 123234, sign: false ]
> jsbi.BigInt(" 123234x")
Thrown:
SyntaxError: Cannot convert  123234x to a BigInt
> jsbi.BigInt(" 123234 x")
JSBI [ 123234, sign: false ]
> jsbi.BigInt(" 123234 ?")
JSBI [ 123234, sign: false ]
> jsbi.BigInt(" 123234 ?a")
Thrown:
SyntaxError: Cannot convert  123234 ?a to a BigInt
```

### PR DESCRIPTION
**Pull request by jakobkummerow**
When there was whitespace and then a single character of non-whitespace
trailing garbage after the BigInt, we failed to look at that last character.

Fixes #36.

### CODE REVIEW

File: tests/tests.mjs [hunk 1]
```diff
@@ -46,6 +46,24 @@ const TESTS = [
   },
 ];
 
+// https://github.com/GoogleChromeLabs/jsbi/issues/36
+(function() {
+  const VALID = ['123', ' 123 ', '   123   '];
+  const INVALID = ['x123', 'x 123', ' 123x', '123 x', '123  xx', '123 ?a'];
+  for (const v of VALID) {
+    let result = JSBI.BigInt(v);
```
Comment (mathiasbynens) [inline tests/tests.mjs]:
```suggestion
    const result = JSBI.BigInt(v);
```

File: tests/tests.mjs [hunk 2]
```diff
@@ -46,6 +46,24 @@ const TESTS = [
...
+    console.assert(JSBI.equal(result, JSBI.BigInt(123)));
+  }
+  for (const i of INVALID) {
+    try {
+      let result = JSBI.BigInt(i);
```
Comment (mathiasbynens) [inline tests/tests.mjs]:
```suggestion
      const result = JSBI.BigInt(i);
```

File: tests/tests.mjs [hunk 3]
```diff
@@ -46,6 +46,24 @@ const TESTS = [
...
+      throw "unreachable";
+    } catch (e) {
```
Comment (mathiasbynens) [inline tests/tests.mjs]:
```suggestion
    } catch (exception) {
```

File: tests/tests.mjs [hunk 4]
```diff
@@ -46,6 +46,24 @@ const TESTS = [
...
+      console.assert(e instanceof SyntaxError);
```
Comment (mathiasbynens) [inline tests/tests.mjs]:
```suggestion
      console.assert(exception instanceof SyntaxError);
```

File: tests/tests.mjs [hunk 5]
```diff
@@ -46,6 +46,24 @@ const TESTS = [
...
+    }
+  }
+})()
```
Comment (mathiasbynens) [inline tests/tests.mjs]:
```suggestion
})();
```
